/**
 * Phase 18 — PPTX cover (D-03, brand-free PPT-02). Ported from vsizer's
 * titleSlide structure: full navy field, gold accent strip, factual eyebrow,
 * big estate-identity title, freshness subtitle, and a 5-tile estate KPI band
 * (hosts / VMs / physical GHz / physical RAM / mean CPU %). No client logo, no
 * editorial tagline. Pure: strings injected.
 */
import type PptxGenJS from 'pptxgenjs'
import type { ExportStrings } from '../../types'
import { type ExportLocale, pptxNumber, pptxSafeFormat } from '../format'
import { PPTX_COLORS } from '../primitives/colors'
import { drawKpiCard } from '../primitives/draw'
import { SLIDE } from '../theme'

export interface TitleData {
  vcenters: string
  clusterCount: number
  hostCount: number
  vmCount: number
  capturedAt: string
  /** Estate physical GHz (branded → number at the call site). */
  physicalGhz: number
  /** Estate physical RAM in MiB. */
  physicalRamMib: number
  /** Estate mean CPU utilization ratio (0..1; ×100 for %). */
  meanCpuRatio: number
}

export function addTitleSlide(
  pptx: PptxGenJS,
  d: TitleData,
  strings: ExportStrings,
  locale: ExportLocale,
): void {
  const s = pptx.addSlide()
  s.background = { color: PPTX_COLORS.primary500 }
  const M = SLIDE.margin
  const W = SLIDE.w - M * 2
  const t = (k: string, fallback: string) => strings[`title.${k}`] ?? fallback
  const n = (v: number) => pptxNumber(v, locale)
  const tib = (mib: number) => `${pptxNumber(mib / 1024 / 1024, locale, 1)} TiB`

  // Eyebrow
  s.addText(pptxSafeFormat(t('eyebrow', 'VMWARE ESTATE')), {
    x: M,
    y: 1.4,
    w: W,
    h: 0.45,
    color: PPTX_COLORS.accent,
    fontFace: 'Arial',
    fontSize: 14,
    bold: true,
  })
  // Big estate-identity title
  s.addText(pptxSafeFormat(d.vcenters || t('fallback', 'VMware estate')), {
    x: M,
    y: 2.0,
    w: W,
    h: 1.6,
    color: 'ffffff',
    fontFace: 'Arial',
    fontSize: 40,
    bold: true,
  })
  // gold factual rule
  s.addShape('rect', {
    x: M,
    y: 3.75,
    w: 2.4,
    h: 0.06,
    fill: { color: PPTX_COLORS.accent },
    line: { type: 'none' },
  })
  const identity =
    strings['title.identity'] ??
    `${n(d.clusterCount)} clusters · ${n(d.hostCount)} hosts · ${n(d.vmCount)} VMs · captured ${d.capturedAt}`
  s.addText(pptxSafeFormat(identity), {
    x: M,
    y: 3.95,
    w: W,
    h: 0.5,
    color: PPTX_COLORS.primary200,
    fontFace: 'Consolas',
    fontSize: 16,
  })

  // Estate KPI band (5 navy tiles, gold values) — vsizer-style.
  const tiles = [
    { big: n(d.hostCount), small: t('kpiHosts', 'hosts') },
    { big: n(d.vmCount), small: t('kpiVms', 'VMs') },
    { big: `${n(Number(d.physicalGhz))} GHz`, small: t('kpiGhz', 'physical capacity') },
    { big: tib(Number(d.physicalRamMib)), small: t('kpiRam', 'physical RAM') },
    {
      big: `${pptxNumber(d.meanCpuRatio * 100, locale)} %`,
      small: t('kpiCpu', 'mean CPU utilization'),
    },
  ]
  const gap = 0.15
  const tw = (W - gap * (tiles.length - 1)) / tiles.length
  tiles.forEach((tile, i) => {
    drawKpiCard(s, {
      x: M + i * (tw + gap),
      y: 5.0,
      w: tw,
      h: 1.5,
      big: tile.big,
      small: tile.small,
      background: PPTX_COLORS.surface700,
      accent: PPTX_COLORS.accent,
      onDark: true,
    })
  })

  s.addText(t('generated', 'Generated by vatlas — factual estate synthesis'), {
    x: M,
    y: 6.85,
    w: W,
    h: 0.4,
    color: PPTX_COLORS.primary200,
    fontFace: 'Arial',
    fontSize: 11,
  })
}
